services:
  mongodb:
    image : mongo
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped

  appdoc-api:
    build:
      context: .
      dockerfile: ./Containerfile
    ports:
      - 8080:8080
    restart: on-failure
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_started